### ISSUE TITLE
Workflow use

### ISSUE THREAD

**Issue by C3n7ral051nt4g3ncy** [p4p1/tryhackme-badge-workflow#9]
Hey! 

Thanks for making this workflow.

- Forked the repo yesterday
- Added the assets folder with the `thm_propic.png` static image inside 
- created the workflows directory with the `tryhackme-badge-workflow.yml`

Getting an error each time I run the workflow, seems it is running on `Node 12` when it should be `Node 16`: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Also, would I be correct in stating there is no need to have a workflow for the TryHackMe static image? because it will update itself automatically when the image is regenerated on TryHackMe.com.
See Issue #4 , the person is told to click on regenerate on TryHackMe, therefore there does not seem to be a need for a workflow.
Link to statement: https://github.com/p4p1/tryhackme-badge-workflow/issues/4#issuecomment-1199508328

<img width="733"  src="https://user-images.githubusercontent.com/104733166/201477720-cc9180c8-395d-450e-abae-af98a52a7c48.png">

Thanks for your input.

**Comment by p4p1** [comment]
Hello, sorry it took me 14days to answer I've been really busy. Yes what you are pointing out is correct since tryhackme updated the way the static image is implemented the repo basically isnt that usefull 😂 I did think from what you wrote that I could add a system to regenerate the static image everyother day on tryhackme through their API, I'll be honest I have no idea when I would sit down and work on it but it's been on my todo list since you posted :)
About the node version I am aware that they updated it I've just been lazy in changing it I might do a quick updated with the new feature and the migration to the updated nodejs version!
FYI, if you wish to edit the repo to add stuff yourself I welcome any merge request 👌

**Comment by C3n7ral051nt4g3ncy** [comment]
@p4p1 Thank you for your response, I will take a look as soon as I can get some time. Pretty much in the same situation as you as currently very busy. Would be great finding a solution.

**Comment by RexRowan** [comment]
It worked but the link keeps on breaking because the png keeps on being rejected.
